spring.application.name=ReservationSystem

# Gmail SMTPを使用してメールを送信する
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# 環境変数からGmailアドレスを取得する
spring.mail.username=${MAIL_USERNAME}

# 環境変数からGmailのアプリパスワードを取得する
spring.mail.password=${MAIL_PASSWORD}

# SMTP認証を有効にする
spring.mail.properties.mail.smtp.auth=true

# TLS通信を有効にする
spring.mail.properties.mail.smtp.starttls.enable=true